language: node_js
node_js:
  - 16
sudo: required
services:
  - docker

before_install:
  - docker build -t godyato/multi-docker -f ./client/Dockerfile.dev ./client

script:
  - docker run godyato/multi-docker npm run test -- --coverage

after_success:
  - docker build -t godyato/multi-client ./client
  - docker build -t godyato/multi-nginx ./nginx
  - docker build -t godyato/multi-server ./server
  - docker build -t godyato/multi-worker ./worker
  # log into the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push these images into the dockerhub
  - docker push godyato/multi-client
  - docker push godyato/multi-nginx
  - docker push godyato/multi-server
  - docker push godyato/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: Multi-docker-env
  bucket_name: elasticbeanstalk-us-east-1-332338351517
  bucket_path: docker-multi
  on: 
    branch: main
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: "$AWS_SECRET_KEY"